import Header from '@/components/Header';
import './globals.css'
import { Open_Sans } from 'next/font/google';
import Footer from '@/components/Footer';

const OpenSans = Open_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={OpenSans.className}>
      <body className='relative flex flex-col items-center'>
        <Header />
        <main className="grow mt-16 max-w-7xl px-6">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
